"""Added validations to HeroPower model

Revision ID: c2284c68be8a
Revises: 11d67a529635
Create Date: 2024-01-15 10:41:33.570029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2284c68be8a'
down_revision = '11d67a529635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strength',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
